<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_pseudonym_sessionpassword</name>
   <tag></tag>
   <elementGuidId>4b996c80-42a3-41d2-a53a-0970f7f1ff16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pseudonym_session_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pseudonym_session_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d24afe2f-fc95-4702-b559-c71fe19df205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic-Input text</value>
      <webElementGuid>65f35e9b-b4c4-4715-b503-b26088776ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>81a1b8f8-bd80-4dbd-9f69-3e7469b1b428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f9aa4032-3004-4991-9e60-22c47f0c8138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pseudonym_session[password]</value>
      <webElementGuid>1db8d22c-4ebc-4586-bc9a-345250a1d33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pseudonym_session_password</value>
      <webElementGuid>404734fb-5bcd-4d32-a80d-4d1dfdf9ba0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pseudonym_session_password&quot;)</value>
      <webElementGuid>fbe5963c-c189-4de7-8519-d56b1f81526c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pseudonym_session_password']</value>
      <webElementGuid>3e0b4208-ba4f-422e-b1ae-a4e629e3300d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[2]/input</value>
      <webElementGuid>cf0d9f04-1fa6-4945-8db2-0fd2c6745cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0b3b1309-48de-413b-a462-3c8032f974a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pseudonym_session[password]' and @id = 'pseudonym_session_password']</value>
      <webElementGuid>795ec341-be5e-4e3b-8460-9d6b9a055989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
