<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_pseudonym_sessionunique_id</name>
   <tag></tag>
   <elementGuidId>63b357aa-248a-43f1-a23c-6dcbd204f94d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pseudonym_session_unique_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pseudonym_session_unique_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b322a85-ca04-496e-8c07-35868ce7e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic-Input text</value>
      <webElementGuid>51c63274-ed5d-44a5-ba3d-eaaf96cadd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>6170e6d4-5b1d-423d-84be-68a89629bdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0799914b-113b-4180-8fde-45579d2ae791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pseudonym_session[unique_id]</value>
      <webElementGuid>81a9c586-f0ef-414d-9d44-07fe0810187a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pseudonym_session_unique_id</value>
      <webElementGuid>41482049-02f8-4f14-a421-191ab7b1f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pseudonym_session_unique_id&quot;)</value>
      <webElementGuid>e6560f50-98cb-486e-be66-6c2ae813b100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pseudonym_session_unique_id']</value>
      <webElementGuid>64f00585-f637-46d2-9de8-54a36459833f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div/input</value>
      <webElementGuid>64ee3db7-eab2-4995-92e6-ff0fb69bf929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7c449186-b700-4042-a32d-85dd709cb5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pseudonym_session[unique_id]' and @id = 'pseudonym_session_unique_id']</value>
      <webElementGuid>1e76a83e-a998-4530-9b95-e5ee0ff28009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
